export const httpErrorCodes = {
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  INVALID_USERNAME: 'INVALID_USERNAME',
  INVALID_TICKET: 'INVALID_TICKET',
  TRIED: 'TRIED',
  UNKNOWN: 'UNKNOWN',
};
