const httpErrorCodes = {
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  UNKNOWN: 'UNKNOWN',

  WATCHER37_INVALID_TICKET: 'WATCHER37_INVALID_TICKET',
  WATCHER37_TRIED: 'WATCHER37_TRIED',
};

export default httpErrorCodes;
